const products = [
  {
    name: "Haldiram's Sev Bhujia",
    category: "Snack & Munchies",
    image: "../images/products/haldirams-sev-bhujia.jpg",
    sale: "Sale",
    discount: "10%",
    price: 21.6,
    oldPrice: 24,
    salesQuantity: 500,
    link: "#",
  },
  {
    name: "NutriChoice Digestive",
    category: "Bakery & Biscuits",
    image: "../images/products/nutriChoice-digestive.jpg",
    sale: "",
    discount: "",
    price: 25,
    oldPrice: 25,
    salesQuantity: 500,
    link: "#",
  },
  {
    name: "Cadbury 5 Star Chocolate",
    category: "Bakery & Biscuits",
    image: "../images/products/cadbury-chocolate.jpg",
    sale: "Buy 1 Get $3.00 Off",
    discount: "",
    price: 35,
    oldPrice: 38,
    salesQuantity: 500,
    link: "#",
  },
  {
    name: "Onion Flavour Potato",
    category: "Snack & Munchies",
    image: "../images/products/onion-flavour-potato.jpg",
    sale: "Hot",
    discount: "40%",
    price: 3,
    oldPrice: 5,
    salesQuantity: 500,
    link: "#",
  },
  {
    name: "Salted Instant Popcorn",
    category: "Instant Food",
    image: "../images/products/salted-instant-popcorn.jpg",
    sale: "",
    discount: "35%",
    price: 11.7,
    oldPrice: 18,
    salesQuantity: 500,
    link: "#",
  },
  {
    name: "Blueberry Greek Yogurt",
    category: "Dairy & Bakery",
    image: "../images/products/blueberry-greek-yogurt.jpg",
    sale: "",
    discount: "40%",
    price: 15,
    oldPrice: 25,
    salesQuantity: 500,
    link: "#",
  },
  {
    name: "Britannia Cheese Slices",
    category: "Dairy & Bakery",
    image: "../images/products/britannia-cheese-slices.jpg",
    sale: "",
    discount: "",
    price: 23,
    oldPrice: 23,
    salesQuantity: 500,
    link: "#",
  },
  {
    name: "Kellogg's Original Cereals",
    category: "Instant Food",
    image: "../images/products/kelloggs-original-cereals.jpg",
    sale: "",
    discount: "15%",
    price: 29.75,
    oldPrice: 35,
    salesQuantity: 500,
    link: "#",
  },
  {
    name: "Slurrp Millet Chocolate",
    category: "Snack & Munchies",
    image: "../images/products/slurrp-millet-chocolate.jpg",
    sale: "Hot",
    discount: "50%",
    price: 5,
    oldPrice: 10,
    salesQuantity: 500,
    link: "#",
  },
  {
    name: "Amul Butter - 500 g",
    category: "Dairy & Bakery",
    image: "../images/products/amul-butter.jpg",
    sale: "",
    discount: "25%",
    price: 13,
    oldPrice: 16.25,
    salesQuantity: 500,
    link: "#",
  },
  {
    name: "Roast Ground Coffee",
    category: "Tea & Coffee",
    image: "../images/products/roast-ground-coffee.jpg",
    sale: "Hot",
    discount: "25%",
    price: 13.5,
    oldPrice: 18,
    salesQuantity: 250,
    link: "#",
  },
  {
    name: "Crushed Tomatoes",
    category: "Fruits & Vegetables",
    image: "../images/products/crushed-tomatoes.jpg",
    sale: "",
    discount: "25%",
    price: 13.5,
    oldPrice: 18,
    salesQuantity: 250,
    link: "#",
  },
  {
    name: "Golden Pineapple",
    category: "Fruits & Vegetables",
    image: "../images/products/golden-pineapple.jpg",
    sale: "Sale",
    discount: "20%",
    price: 14.4,
    oldPrice: 18,
    salesQuantity: 250,
    link: "#",
  },
  {
    name: "Fresh Apple",
    category: "Fruits & Vegetables",
    image: "../images/products/fresh-apple.jpg",
    sale: "",
    discount: "25%",
    price: 19.2,
    oldPrice: 24,
    salesQuantity: 250,
    link: "#",
  },
  {
    name: "Fresh Banana",
    category: "Fruits & Vegetables",
    image: "../images/products/fresh-banana.jpg",
    sale: "Hot",
    discount: "50%",
    price: 2.5,
    oldPrice: 5,
    salesQuantity: 250,
    link: "#",
  },
];

const originalProducts = [...products]; 
